### PR TITLE
Added functions to Client.php to allow parameters to be passed in URL

### PR DESCRIPTION
**Pull request by tbielek**
What does this PR do?
Added functions getWithParams and startGetWithParams to Client.php to allow parameters to be passed in a URL string in addition to resource and id. There are no changes to existing functions so there are no backward compatibility issues. 

Background
This change was necessary to support the new Nebulous ReportsController. This controller was added to support the ability of AWACS to pull the TOL Lead Reports Summary from Nebulous instead of querying Oracle directly (The report is accessed from the AWACS menu: Reports->Top Reports->TOL Lead Reports Summary).

With this change, realmId, start and end date are passed as parameters in the URL to the nebulous ReportsController which executes a sql query and returns the results. Previously, Client.php only supported passing of resource & id in the URL.

What are the relevant tickets?
MMT-203

What are the related pull requests?
1) TOL-Rec/tol PR PR #404
2) TOL-Arch/nebulous PR #459

What applications and/or websites is this PR expected to affect?
1) AWACS TopBusinessReport. The report is accessed from the AWACS menu: Reports->Top Reports->TOL Lead Reports Summary.
2) Nebulous ReportsController.php 

This change adds functions without changing any existing functions so there are no backward compatibility issues.  

Dependencies
None

### CODE REVIEW

**Comment by tbielek** [comment]
@guywithnose @chadicus @jason-wogan Please review

**Comment by chadicus** [comment]
I would suggest NOT using this library and instead just use the `CommerceGuys` [OAuth2 Plugin](https://github.com/commerceguys/guzzle-oauth2-plugin) for `Guzzle`  

```php
use GuzzleHttp\Client;                                                                                                   
use CommerceGuys\Guzzle\Oauth2\GrantType\ClientCredentials;                                                              
use CommerceGuys\Guzzle\Oauth2\Oauth2Subscriber;                                                                         

$baseUrl = 'https://apis.traderonline.com/v1/';  //MUST have tailing slash                                              
                                                                                                                         
//config for getting access tokens                                                                                       
$config = [                                                                                                              
    'client_id' =>  'client',
    'client_secret' => 'secret',
    'token_url' => 'token',                                                                                              
];                                                                                                                       
                                                                                                                         
//set-up the subscriber. This will automatically obtain access tokens for you                                            
$subscriber = new Oauth2Subscriber(                                                                                      
    new ClientCredentials(                                                                                               
        new Client(['base_url' => $baseUrl]),                                                                            
        $config                                                                                                          
    )                                                                                                                    
);                                                                                                                       
                                                                                                                         
//create the client for requests against the API                                                                         
$client = new Client(                                                                                                    
    [                                                                                                                    
        'defaults' => [                                                                                                  
            'auth' => 'oauth2',                                                                                          
            'subscribers' => [$subscriber], //use the subscriber here                                                    
        ],                                                                                                               
        'base_url' => $baseUrl,                                                                                          
    ]                                                                                                                    
);      

//any requests made against the API will automatically use the access tokens
$response = $client->get('resource/id?foo=bar');

//access the json response by using

**Comment by chadicus** [comment]
@tbielek 

Another alternative which would not require any code changes would be to use the `index` method with an `id` parameter

```php
$client->index('/resource', ['id' => 'the id, 'aParam' => 'foo', 'anotherParam' => 'bar']);
```

While I still think the guzzle plugin should be used instead of this library, you can get the functionality you need by using the above example without any code changes needed.

**Comment by tbielek** [comment]
Closing PR. Implemented suggested approach using index function which does not require a code change

**Pull request closed without merging**
